@TodoApi_HostAddress = https://localhost:7277

POST {{TodoApi_HostAddress}}/todoitems
Content-Type: application/json

{
  "Name":"walk dog",
  "isComplete":true
}

###

GET {{TodoApi_HostAddress}}/todoitems

###

@id=1
DELETE {{TodoApi_HostAddress}}/todoitems/{{id}}

###

GET {{TodoApi_HostAddress}}/todoitems/{{id}}

###

PUT {{TodoApi_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  "Name":"walk dog sex",
  "isComplete":false
}

###
